urls.py
from django.conf.urls.defaults import patterns, include, url

from django.contrib import admin
from django.conf import settings

from apps.urls import urlpatterns as apps_urlpatterns
from views import RoomsPricesView, ChangeRoomPriceView, CreatePricesView, SavePriceTypeView, SaveSeasonView, CreateSeasonView

admin.autodiscover()

urlpatterns = patterns('',
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),

    # Admin
    url(r'^admin/rooms_prices/$', RoomsPricesView.as_view(), name='admin_rooms_prices_url'),
    url(r'^admin/change_room_price/$', ChangeRoomPriceView.as_view(), name='admin_change_room_price_url'),
    url(r'^admin/create_prices/$', CreatePricesView.as_view(), name='admin_create_prices_url'),
    url(r'^admin/save_price_type/$', SavePriceTypeView.as_view(), name='admin_save_price_type_url'),
    url(r'^admin/save_season/$', SaveSeasonView.as_view(), name='admin_save_season_url'),
    url(r'^admin/create_season/$', CreateSeasonView.as_view(), name='admin_create_season_url'),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^admin_tools/', include('admin_tools.urls')),
	(r'^admin/crop/(?P<app_name>\w+)/(?P<model_name>\w+)/(?P<id>\d+)/$', 'views.crop_image_view'),

     #Redactor
    (r'^upload_img/$', 'views.upload_img'),
    (r'^upload_file/$', 'views.upload_file'),

    # favicon
    (r'^favicon\.ico$', 'django.views.generic.simple.redirect_to', {'url': '/static/images/favicon.ico'}),

)

urlpatterns += apps_urlpatterns

apps/press/models.py
# -*- coding: utf-8 -*-
import os, datetime

from pytils.translit import translify

from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

from sorl.thumbnail import ImageField

from apps.utils.managers import PublishedManager

def image_file_path(instance, filename):
    return os.path.join('images', 'press', instance.__class__.__name__.lower(), translify(filename).replace(' ', '_') )

class PressItem(models.Model):
    title = models.CharField(verbose_name=u'название', max_length=150)
    short_text = models.TextField(verbose_name=u'короткий текст', blank=True)    
    text = models.TextField(verbose_name=u'текст')
    date_add = models.DateField(verbose_name=u'дата добавления', default=datetime.date.today())
    is_published = models.BooleanField(verbose_name=u'опубликовано', default=True)
    press_type = models.CharField(verbose_name=u'тип', max_length=150, editable=False)
    press_type_slug = models.CharField(verbose_name=u'слаг типа', max_length=150, editable=False)

    objects = PublishedManager()

    class Meta:
        verbose_name = u'пресс релиз'
        verbose_name_plural = u'пресс релизы'
        ordering = ['-date_add']

    def __unicode__(self):
        return self.title


class NewsItem(PressItem):
    objects = PublishedManager()

    class Meta:
        verbose_name = u'новость'
        verbose_name_plural = u'новости'

    def __unicode__(self):
        return self.title

    def save(self):
        if self.pk is None:
            self.press_type = 'новость'
            self.press_type_slug = 'news'
        super(NewsItem, self).save()

    
class SpecialOffer(PressItem):
    image = ImageField(verbose_name=u'картинка', upload_to=image_file_path)
    date_from = models.DateField(verbose_name=u'дата начала', blank=True, null=True)
    date_to = models.DateField(verbose_name=u'дата окончания', blank=True, null=True)
    show_in_slider = models.BooleanField(verbose_name=u'показывать в слайдере', default=True)

    objects = PublishedManager()

    class Meta:
        verbose_name = u'специальное предложение'
        verbose_name_plural = u'специальные предложения'

    def __unicode__(self):
        return self.title

    def save(self):
        self.press_type = 'специальное предложение'
        self.press_type_slug = 'special_offer'
        super(SpecialOffer, self).save()


class PhotoReport(PressItem):
    objects = PublishedManager()

    class Meta:
        verbose_name = u'фотоотчет'
        verbose_name_plural = u'фотоотчеты'

    def __unicode__(self):
        return self.title

    def save(self):
        self.press_type = 'фотоотчет'
        self.press_type_slug = 'photoreport'
        super(PhotoReport, self).save()


class PressPhoto(models.Model):
    photo_report = models.ForeignKey(PhotoReport, verbose_name=u'фототчет')
    title = models.CharField(verbose_name=u'название', max_length=150, blank=True)
    image = ImageField(verbose_name=u'картинка', upload_to=image_file_path)

    class Meta:
        verbose_name = u'фотография'
        verbose_name_plural = u'фотографии'

    def __unicode__(self):
        return self.title

apps/press/views.py
# -*- coding: utf-8 -*-
from django.http import Http404, HttpResponse, HttpResponseBadRequest, HttpResponseRedirect, HttpResponseForbidden
from django.template.loader import render_to_string
from django.views.decorators.csrf import csrf_exempt
from django.views.generic.simple import direct_to_template

from django.views.generic import ListView, DetailView, TemplateView

from models import *


class PressListView(ListView):
    template_name = 'press/press_list.html'
    context_object_name = 'press_list'
    paginate_by = 7

    def get_queryset(self):
        press_type = self.request.GET.get('press_type')

        if press_type:
            try:
                press_list = PressItem.objects.published().filter(press_type_slug=press_type)
            except:
                press_list = PressItem.objects.published()
        else:
            press_list = PressItem.objects.published()

        return press_list


class PressItemView(DetailView):
    model = PressItem

templates/press/press_list.html
{% extends 'base.html' %}

{% load thumbnail siteblocks_extras pymorphy_tags %}

{% block content %}
<div class="page">
    {% include 'about_header.html' %}

    <div class="column-4">
        <ul class="press-menu">
            <li {%if not request.GET.press_type%}class="current"{%endif%}><span><a href="{{request.path}}">Все записи</a></span></li>
            <li {%if request.GET.press_type == 'news'%}class="current"{%endif%}><span><a href="{{request.path}}?press_type=news">Новости</a></span></li>
            <li {%if request.GET.press_type == 'special_offer'%}class="current"{%endif%}><span><a href="{{request.path}}?press_type=special_offer">Специальные предложения</a></span></li>
            <li {%if request.GET.press_type == 'photoreport'%}class="current"{%endif%}><span><a href="{{request.path}}?press_type=photoreport">Фотоотчеты</a></span></li>
        </ul>
    </div>
    <div class="column-16">
        {% for press_item in press_list %}
        <div class="column-14 press-item">
            <div class="press_type">
                <span>{{press_item.press_type|capfirst}}</span>
            </div>
            <div class="press-title">
                <span class="title"><h2><a href="{% url press_item_url press_item.id %}">{{press_item.title}}</a></h2></span>
                <span class="date">{{press_item.date_add|date:"j E Y"}}</span>
            </div>
            <div class="press-image">
                <a href="{% url press_item_url press_item.id %}" class="img-link">
                    {% if press_item.specialoffer %}
                        {% thumbnail press_item.specialoffer.image "600" upscale=False format="PNG" as im %}
                            <img class="with-shadow" src="{{im.url}}" alt="" width="{{im.width}}" height="{{im.height}}">
                        {% endthumbnail %}
                    {% elif press_item.news %}
                        {% thumbnail press_item.news.image "600" upscale=False format="PNG" as im %}
                            <img class="with-shadow" src="{{im.url}}" alt="" width="{{im.width}}" height="{{im.height}}">
                        {% endthumbnail %}
                    {% endif %}
                </a>
            </div>
            <div class="press-short-text">
                {{press_item.short_text}}
            </div>
            {% if press_item.photoreport %}
            <div class="photoreport-previews">
                {% for pressphoto in press_item.photoreport.pressphoto_set.all %}
                <div class="photo-preview">
                {% thumbnail pressphoto.image "76x76" format="PNG" crop="center" as im %}
                    <img class="with-shadow" src="{{im.url}}" alt="">
                {% endthumbnail %}
                </div>
                {% endfor %}
            </div>
            {% endif%}
        </div>
        {% empty %}
        <div class="column-14 press-item">
            ...
        </div>
        {% endfor %}

        <div class="column-16">
            {% if is_paginated and page_obj.paginator.num_pages > 1 %}
                {% include 'pagination.html' %}
            {% endif %}
        </div>
    </div>
    <div class="column-4 special">
        {% get_sidebar_order %}
    </div>
</div>
{% endblock %}

{% block footer_class %}
waved
{% endblock %}

templates/press/pressitem_detail.html
{% extends "base.html" %}

{% load thumbnail siteblocks_extras %}

{% if page.title %}
    {% block title %}
        {{ page.title }} &mdash;
    {% endblock %}
{% endif %}

{% block content %}
<div class="page">
    {% include 'about_header.html' %}

    <div class="column-20">
        <div class="column-4">
            <a href="/full_map/" class="img-link">
                {% if summer_or_winter == 'summer' %}
                    <img src="/static/images/minimap-summer.png" width="120">
                {% else %}
                    <img src="/static/images/minimap-winter.png" width="120">
                {% endif %}
            </a>
            <p><a href="/full_map/">Карта курорта</a></p>
        </div>

        <div class="column-16 main-text-column press-item">
            <h1>{{ pressitem.title }}</h1>
            <div class="press-image">
                {% if pressitem.specialoffer %}
                    {% thumbnail pressitem.specialoffer.image "600" upscale=False format="PNG" as im %}
                        <img class="with-shadow" src="{{im.url}}" alt="" width="{{im.width}}" height="{{im.height}}">
                    {% endthumbnail %}
                {% elif pressitem.news %}
                    {% thumbnail pressitem.news.image "600" upscale=False format="PNG" as im %}
                        <img class="with-shadow" src="{{im.url}}" alt="" width="{{im.width}}" height="{{im.height}}">
                    {% endthumbnail %}
                {% endif %}
            </div>
            <div class="redactor text-column">
                {{ pressitem.text|safe }}
            </div>
            {% if pressitem.photoreport %}
            <div class="photoreport-previews">
                {% for pressphoto in pressitem.photoreport.pressphoto_set.all %}
                <div class="photo-preview">
                    {% thumbnail pressphoto.image "600" upscale=False format="PNG" as im %}
                    <img class="with-shadow" src="{{im.url}}" alt="" width="{{im.width}}" height="{{im.height}}">
                    {% endthumbnail %}
                </div>
                {% endfor %}
            </div>
            {% endif%}
        </div>
    </div>

    {% get_sidebar_two_addresses %} 
</div>
{% get_special_offers_slider waved='True' %}

{% endblock %}